---
title: Ontario Voters' Issue Priorities in the 2022 Election Campaign
author: Simon Kiss
date: '2023-01-31'
slug: []
categories:
  - LISPOP
tags:
  - public-opinion
subtitle: ''
summary: ''
authors: []
lastmod: '2023-01-31T19:28:25-05:00'
featured: no
draft: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

Tests
```{r setup, include=FALSE, eval=T, echo=F, message=F, results='hide'}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE, 
                      results='show', cache=FALSE, autodep=FALSE)

knitr::opts_knit$set(root.dir = '../external_data/Ontario_Housing')


```


```{r load-data}

setwd("../external_data/Ontario_Housing")
source("R_Scripts/2_recodes.R")
```

```{r }

glimpse(on22)

```


```{r make-week}
#Make a weekvariable
on22$Week<-cut(on22$StartDate, "weeks")
library(lubridate)
on22$Day<-day(on22$StartDate)
on22 %>% 
  group_by(Interest, Topic) %>% 
  summarize(n=n()) %>% 
  arrange(Interest, desc(n)) %>% 
  filter(str_detect(Topic, "Other", negate=T)) %>% 
filter(str_detect(Topic, "know", negate=T)) %>% 
  filter(str_detect(Topic, "None", negate=T)) %>% 
    filter(str_detect(Topic, "Refused", negate=T)) %>% 
  filter(!is.na(Interest)) %>% 
  mutate(Percent=(n/sum(n))*100) %>% 
  slice_max(Percent, n=3) %>% 
  ggplot(., aes(y=fct_reorder(Topic, Percent), x=Percent, fill=fct_relevel(Interest, "High", "Medium", "Low")))+
  geom_col(position="dodge")+
  scale_fill_manual(values=c("red", "green", "blue"), guide=guide_legend(reverse=T))
```

