---
title: 'Academic Hiring in Ontario'
author: 'Sinon Kiss'
date: '2020-02-20'
slug: test
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2020-02-20T14:34:04-05:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

```{r echo=F, results='markup', warning=F, message=F}
library(knitr)
opts_chunk$set(results='markup', warning=F, message=F, echo=F)
```

First thing is to read in all the data. If we go to the sunshine lists's page and look at the URLs for all of the data, the filenames are formatted very nicely. 

`https://files.ontario.ca/en-1997-pssd.csv`
`https://files.ontario.ca/en-1996-pssd.csv`

But, it also looks like starting in 2010, the filenames change patters. 
`https://files.ontario.ca/2010.csv`

And it looks like 2012 changes. 

`https://files.ontario.ca/pssd-en-2012-fixed_0.csv`
And the 2018 file name is different yet again. 

`https://files.ontario.ca/en-2018-pssd-compendium-utf8_1.csv`

So we can paste together a list of all the CSV files with this command. 

```{r make-urls}

years<-seq(1996,2009, by=1)


urls<-paste0('https://files.ontario.ca/en-', years, '-pssd.csv')

#we need to change 2012
urls[15]<-'https://files.ontario.ca/2010.csv'
urls[16]<-'https://files.ontario.ca/2011.csv'
urls[17]<-'https://files.ontario.ca/pssd-en-2012-fixed_0.csv'
urls[18]<-'https://files.ontario.ca/pssd-en-2013.csv'
urls[19]<-'https://files.ontario.ca/2014-pssd-full-compendium-utf8-en.csv'
urls[20]<-'https://files.ontario.ca/pssd/en-2015-pssd-compendium-with-addendum-20161219.csv'
urls[21]<-'https://files.ontario.ca/en-2016-pssd-compendium-20171128-utf8.csv'
urls[22]<-'https://files.ontario.ca/en-2018-pssd-compendium.csv'
urls[23]<-'https://files.ontario.ca/en-2018-pssd-compendium-20191223.csv'

```

```{r get-salary-data,cache=T}
library(tidyverse)
library(purrr)

urls %>% 
  map(., read_csv)-> out


```


```{r modify-names, results='asis'}


library(tidyverse)
library(stringr)
library(magrittr)
library(purrr)

out %>% 
 map(., extract, c(1:8)) %>% 
  map(., rename, `Last name`=2,
      `Job Title`=7,
      `Year`=8) %>% 
  map_df(., mutate, `Salary Paid`=str_replace(`Salary Paid`, '\\$', ''), `Taxable Benefits`=str_replace(`Taxable Benefits`, '\\$', '')) %>% 
  mutate(., Salary=str_replace(`Salary Paid`, "\\,", ""),
         Benefits=str_replace(`Taxable Benefits`, "\\,", "")) %>% 
  mutate(., Salary=as.numeric(Salary), Benefits=as.numeric(Benefits), 
         Total=sum(Salary,Benefits, na.rm=T)) ->out2
```


```{r recode-odd-titles}
out2 %>% 
  mutate(job=case_when(
    str_detect(`Job Title`, 'Professor') ~"Academic",
        str_detect(`Job Title`, 'Canada Research Chair') ~"Academic",
    str_detect(`Job Title`, 'Lecturer') ~"Academic",
    str_detect(`Job Title`, 'Faculty') ~"Academic",
    str_detect(`Job Title`, "Librar") ~"Academic",
    str_detect(`Job Title`, 'Prof.') ~"Academic",
    str_detect(`Job Title`, 'Physician') ~NA_character_,
    str_detect(`Job Title`, 'Chair') ~"Academic",
    str_detect(`Job Title`, 'Dean') ~"Academic",
    str_detect(`Job Title`, 'Principal') ~"Academic",
    str_detect(`Job Title`, 'Research Associate') ~"Academic",
    str_detect(`Job Title`, 'Clinician')~ NA_character_,
    str_detect(`Job Title`, 'Department Head')~ "Academic",
    str_detect(`Job Title`, 'Research Director')~ "Academic",
    str_detect(`Job Title`, 'Research Manager')~ "Academic",
    str_detect(`Job Title`, 'Queen\'s National Scholar')~ "Academic",
    str_detect(`Job Title`, 'Molecular Biologist')~ "Academic",
    str_detect(`Job Title`, 'Senior Researcher')~ "Academic",
    str_detect(`Job Title`, 'Psychologist')~ "Academic",
    str_detect(`Job Title`, 'Contract Academic Staff')~ "Academic",
    str_detect(`Job Title`, 'Clinical Research Coordinator')~ NA_character_,
    str_detect(`Job Title`, 'Manager, Analytical Biology')~ "Academic",
    str_detect(`Job Title`, 'Director, Sudbury Neutrino')~ "Academic",
    str_detect(`Job Title`, 'Director Wilfrid Laurier Press')~ "Academic",
    str_detect(`Job Title`, 'Tutor')~ "Academic",
    TRUE ~ "Non-Academic"
  )
  ) %>% 
  filter(Sector=="Universities") ->out3
 # group_by(job) %>% 
 #  summarize(n=n()) %>% 
 #  arrange(desc(n))

```
```{r set-theme}
theme_set(theme_bw())

```
```{r how-many}
out3 %>% 
  ggplot(., aes(x=Year, fill=job))+geom_bar(position="dodge")
```


```{r}

out3 %>% 
 group_by(Year, job) %>% 
  summarize(n=n(), average=mean(Total)) %>% 
  ggplot(., aes(x=Year, col=job, y=average))+geom_point()


```




