---
title: Research Assistantship Examining Class Voting in Canada
author: Simon Kiss
date: '2019-08-28'
slug: research-assistantship-examining-class-voting-in-canada
categories: []
tags: []
header:
  caption: ''
  image: ''
---

### Job Description 

We are seeking a part-time research assistant for the Fall of 2019 to assist a SSHRC-funded research project examining the evolution of the organization of the New Democratic Party of Canada. Part of this project involves examining correlates of support for the NDP over a multi-decadal time span, with a particular emphasis on the different dimensions of social class. 

The primary task for the RA will be to construct a time series data set from the Canada Election Studies.  This will involve writing code that:

- Loads data files
- selects variables of interest to the researchers
- Conducts any recodes for missing values and for scaling purposes
- Renames variables consistently

There is potential for further work in the event that the successful candidate is interested.

### Qualifications
At least a Master’s degree in the social sciences with demonstrated experience in quantitative research. 

It would be useful for the candidate to have a demonstrated scholarly interest in issues of social class, stratification or economic inequality as well as voting behaviour.

Ideally, the successful candidate will have strong capabilities in R. The research group is prepared to invest in some training courses for the candidate to develop this facility.

### Working conditions 
The hours are flexible and the work can be conducted remotely.  Start and completion date are flexible, but ideally will occur in the Fall 2019 academic term. The employee will report primarily to Dr. Simon Kiss at Wilfrid Laurier University and secondarily to [Dr. Peter Graefe](https://socialsciences.mcmaster.ca/people/graefe-peter) at McMaster University

The project is expected to take between 30 and 50 hours of work, although this is flexible. 

### Salary
The salary for the successful candidate will range from C$22-C$28 for Master’s students (or graduates) and C$28 - C$33 for doctoral students (or graduates). 

### Contacts 
|   |   |
|-----------------------------|-------------------------|
|Simon Kiss |Peter Graefe |
Associate Professor | Associate Professor |
Digital Media and Journalism	| Political Science | 
Wilfrid Laurier University |	McMaster University |
skiss at wlu dot ca	| graefep at mcmaster dot ca |